:toc:
:toc-placement!:

= gsheet

toc::[]

== Introduction

`gsheet` is a cli tool for sending and receiving csv data to and from Google Sheets.

With `gsheet` you can:

- Pipe csv data from stdin to a Google Sheet range
- Pipe csv data from a Google Sheet range to stdout
- Clear a Google Sheet range
- Create and delete sheets of a Spreadsheet document
- Sort a sheet by a column
- Download Google Sheet documents from Google Drive as .csv files
- Upload .csv files to Google Drive as Sheet documents
- (You can also upload/delete arbitrary files to/from Google Drive, though `gsheet` isn't trying to be a general purpose gdrive interface)

`gsheets` supports authenticating with Google using https://cloud.google.com/iam/docs/understanding-service-accounts[service accounts], which is a simple way to allow scripts to acces Google Sheets (see <<auth>> below).

=== Why?

I often write scripts and cron jobs for clients that create tabular reports, and I've found that Google Sheets is a convenient way to expose them on the web (easy to use, built-in access control). In addition, I've found that setting up a Sheet with a few fields that my script can read is a convenient way to allow clients to configure apps without needing to build a web interface just to get a few runtime config values.

== Installation

I will update this README with installation and usage instructions when I think it is ready to be used by other people.

[#auth]
== Authentication and Authorization

The hardest part about getting started with `gsheet` is creating the API credentials so that the program can access Google Drive, but it's not so bad and you only have to do it once. In order for `gsheet` to read and update Sheets documents, it must 1) be provided credentials to authenticate with Google and 2) be granted access to whichever Google Drive folders/documents you want to be accessible to it:

. Create a service account and download the credentials .json file to the computer you will use `gsheet` on
** From the https://console.cloud.google.com/home/dashboard[Google Cloud API Dashboard] create a new project and enable both the `Google Drive API` and the `Google Sheets API` on it. See https://cloud.google.com/apis/docs/getting-started[Google's Getting Started Guide] for creating a project and enabling APIs.
** From your project's dashboard Click on "IAM & Admin" > "Service Accounts". Then click "Create Service Account". For the service account's role I recommend "Basic>Editor".
** Once the service account is created, click on it to manage its details. From the "Keys" tab click "Add Key" to create credentials in a .json file for the service account that `gsheet` will use to authenticate as the user.
*** The .json file containing the credentials should download automatically. KEEP THIS FILE SECRET. Anyone with the credentials can edit any files you grant the service account access to.
*** Google's documentation is available as https://cloud.google.com/iam/docs/creating-managing-service-accounts[Creating and Managing Service Accounts] and https://cloud.google.com/iam/docs/creating-managing-service-account-keys[Creating and Managing Service Account Keys]
** Set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to the path to the .json file. This is how `gsheet` finds the credentials when it runs. (See https://cloud.google.com/docs/authentication[Google's Authentication Overview].)
. In Google Drive grant access to the service account (the email address generated when you created the service account above) to any folders or files you want to be able to access with `gsheet`. Note that if you only want to store files in the service account's own drive (not viewable from the Google Drive web interface), then you don't actually have to grant it access to any of your folders or documents.

=== What about OAuth authentication?

Currently `gsheet` only supports service accounts which, depsite the convoluted instructions above, are simple to generate and use once you figure it out (you just need a single .json file with credentials to grant a script access to Google Drive files).

However, if an OAuth workflow (where you can authenticate `gsheet` using your own Google account) would be useful to someone, I'm open to implementing it. Feel free to create an issue. In the mean time check out https://github.com/simon3z/gsheetcsv[simon3z/gsheetcsv] which is another simple cli tool in Go which allows interacting with Google Sheets and uses OAuth for authentication.

== CLI Usage

== Use as Golang Package

== Hack
